import type { BallResult, GameState } from "@/hooks/useHandCricket";

interface CommentaryContext {
  game: GameState;
  result: BallResult;
}

const BATTING_RUNS: Record<string, string[]> = {
  "0": [
    "Dot ball! No run scored.",
    "Defence holds — zero off that ball.",
    "Good bowling! Nothing from that delivery.",
    "Played and missed! No damage done.",
    "Stone-cold defence — dot ball.",
    "Dead bat. Zero runs. Smart play.",
    "Left alone beautifully — nothing scored.",
    "Tight line, tighter defence. Dot.",
    "That's going nowhere. Zero runs.",
    "Blocked it right back. No run.",
    "Solid wall of defence! Dot ball.",
    "Nothing doing there. Good leave.",
    "Rock solid! No runs off that.",
    "Watchful batting. Dot ball.",
    "The bowler wins that battle. Zero.",
    "Shouldered arms. Nothing scored.",
    "Defence like a fortress! Dot.",
    "Can't find the gap. No run.",
    "Textbook block. Zero runs added.",
    "Playing it safe — dot ball on the board.",
    "Respect shown to a great delivery. Dot ball.",
    "That one nipped back — safely blocked.",
    "Patient approach here. No run needed.",
    "Eyes on the ball, bat behind it. Dot.",
    "A maiden-worthy delivery. Zero runs.",
    "The batter decided to leave it alone. Smart!",
    "Defended with soft hands. No run.",
    "Not offering a shot — wise decision.",
    "The bowler is asking questions! No run.",
    "Survival instinct kicks in. Dot ball.",
    "Playing the long game here. Zero.",
    "Back foot defence, solid as a rock.",
    "Forward press, meets it perfectly. No run.",
    "Seam movement beaten the outside edge! Dot.",
    "Length ball kept out. No damage.",
    "That's a beauty! But defended well. Zero.",
    "Almost got an edge! Lucky dot ball.",
    "Tremendous restraint from the batter. Dot.",
    "The bowler celebrates a maiden delivery!",
    "Gritted out! That wasn't easy, but it's a dot.",
    "Left alone outside off stump. Smart batting.",
    "Rock and block! No run off that one.",
    "Padded away on the back foot. Dot ball.",
    "The battle within the battle. Another dot.",
    "Can't lay bat on that one. Zero runs.",
    "Solid forward defence. The crowd waits.",
    "Blocked with conviction. Nothing doing.",
    "Smothered the spin perfectly. Dot ball.",
    "Negotiated that beauty! No run, but well played.",
    "Played from the crease — no intent to score there.",
    "The bowler pumps his fist! Another dot!",
    "Can't break through this defence. Dot.",
    "Tight bowling meets tighter batting. Zero.",
    "Survives! That was close but no run.",
    "Back to basics. Defence first. Dot ball.",
    "Beaten for pace! Lucky no edge. Dot.",
    "Stiff forward defence. Like a wall. Zero.",
    "Maiden delivery material. No run scored.",
    "The batter digs in. Another dot ball.",
  ],
  "1": [
    "Nudged away for a single.",
    "Quick single taken!",
    "One run added to the total.",
    "Rotates the strike with a single.",
    "Cheeky single — smart cricket.",
    "Tucked off the pads for one.",
    "Worked it away — one run.",
    "Pushes to mid-on, easy single.",
    "Just the one, but it ticks along.",
    "Milking the bowling — one more.",
    "Dabbed to third man for one.",
    "Flicked off the hip — single!",
    "Turned the face, picks up one.",
    "Soft hands, single to fine leg.",
    "Good running! One to the total.",
    "Nurdles it behind square for one.",
    "Just a single, but keeps the board moving.",
    "Smart placement for a quick single.",
    "Works it square for one run.",
    "Gentle push — one run scored.",
    "Tapped to point and they scurry through for one.",
    "Eased into the gap — quick single!",
    "Off the mark with a neat single.",
    "Clips it off the toes — one run.",
    "Steered to gully — a brisk single.",
    "Pushes to the off side and runs hard — one.",
    "Dropped it at his feet and stole a single!",
    "Late cut — just the one but well judged.",
    "Glanced to leg — easy single.",
    "That's the hundred partnership builder — a single.",
    "Smart cricket! No need for heroics, just a single.",
    "Controlled push — one run.",
    "Leg glance for a comfortable single.",
    "Squeezed through the field for one.",
    "Opens the face, guides it for one.",
    "Deft touch! Single to fine leg.",
    "Scrambled through for a quick single!",
    "That nearly stuck in the pitch! A single though.",
    "Quick hands, quicker feet — one run.",
    "Angled the bat — single to third man.",
    "Punched to cover — they take one.",
    "Played to the leg side — single.",
    "Nice footwork and a push for one.",
    "Negotiated that and takes a quick single.",
    "Keeps the scoreboard ticking. One run.",
    "Expert rotation of strike — another single.",
    "No risk, just reward. One run.",
    "Worked off the pads for a single.",
    "Deflected fine — one run taken.",
    "Placed it perfectly for a quiet single.",
    "Minimal fuss, maximum efficiency — one run.",
    "The singles add up! Another one here.",
    "Off the back foot — one to the leg side.",
    "Pushes down the ground — one run.",
    "Smart batting — uses the pace for a single.",
    "Drops and runs — clever single!",
    "Inside edge and they steal a single!",
    "Whips it off the hip — one run.",
    "Takes the aerial route... no, grounded for one.",
  ],
  "2": [
    "Nicely placed for two!",
    "Great running between the wickets — two runs.",
    "Pushed into the gap, two taken!",
    "Lovely placement! Two runs scored.",
    "Quick between the stumps — two!",
    "Splits the fielders for a brace.",
    "Driven down the ground — two more!",
    "Two runs! Expert gap-finding.",
    "Gorgeous timing, and that's two.",
    "Athletic running gets them two!",
    "Cuts hard, fielder chases — two runs.",
    "Pulls it to deep square — two!",
    "Clips it fine — two runs taken.",
    "Threads the needle for two!",
    "Sharp running converts one to two!",
    "Glanced off the pads — two runs.",
    "Swept fine — comfortable two.",
    "Cover drive! They'll come back for two.",
    "Punched through extra cover — two!",
    "Great call for two! Smart running.",
    "Racing between the wickets — two more!",
    "Turned the face on that one — a couple!",
    "Pierced the infield for a handy two.",
    "Square cut and the ball races — two!",
    "Beautifully weighted placement — two runs.",
    "Pushed to long-off and they hustle back for two!",
    "That's clever batting — two runs with zero risk.",
    "Worked behind square for two. Good awareness!",
    "Lofted safely — just the two but well played.",
    "Nurdled to deep square leg — two comfortable runs.",
    "Exquisite footwork and two runs scored!",
    "Cracked off the back foot — two to the boundary rope!",
    "Driven elegantly — the outfielder saves the boundary, two!",
    "Steered to deep third man — two more!",
    "Good placement past the diving fielder — two!",
    "Comes down the track and lofts for two!",
    "Paddle swept fine — two runs!",
    "Inside out over cover — held up, just two.",
    "Strong bottom hand — forces it for two!",
    "Whipped through midwicket — two runs, great running!",
    "Drops it short and they capitalize — two!",
    "Turned to the on-side — two comfortable runs.",
    "Off the meat of the bat — two runs!",
    "Controlled aggression — two to the rope!",
    "Opens the face beautifully — two to third man!",
    "Hard run two! The throw just misses the stumps!",
    "Clipped through midwicket — two more to the total!",
    "Back foot punch — two runs scored nicely!",
    "Late cut past the keeper — two for the batter!",
    "Cross-batted pull — gets two with ease!",
    "Feathered to fine leg — two runs taken!",
    "Placed between mid-on and mid-off — two!",
    "Upper cut — just short of the boundary, two!",
    "Muscled through the leg side — two runs!",
    "Quick feet and quicker running — two more!",
    "Guided past gully — two to third man!",
    "Inside-out push — two runs to sweeper cover!",
    "Controlled flick — two more added!",
    "Power-play batting! Punched for two!",
    "Smart cricket — push and run for two!",
  ],
  "3": [
    "Three runs! Excellent placement.",
    "They've run three! Good athleticism.",
    "Three to the total — smart cricket!",
    "Cracked into the gap — three taken!",
    "Outstanding running! Three runs.",
    "Finds the deep and runs three!",
    "Three! Superb work between the wickets.",
    "Driven hard — three runs!",
    "Misfield helps — three to the batter.",
    "Lofted over mid-off — three runs!",
    "Pulled to deep midwicket — three!",
    "Three all the way! Good acceleration.",
    "Quick feet, quick runs — three!",
    "The fielder slips! Three runs taken.",
    "Hammered through the gap — three!",
    "Great power! They come back for three.",
    "Three more to the tally — lovely shot!",
    "Cuts it late — three runs! Beautiful.",
    "Electric between the wickets — three runs!",
    "Diving stop can't prevent three!",
    "What running! Three runs to this powerful batter!",
    "Drilled to the deep — the relay throw comes in, but three already!",
    "Push to long-on and the outfielder fumbles! Three!",
    "Swept hard — ball hits the boundary board but bounces back. Three!",
    "Launched towards the fence — just short! Three taken!",
    "Picked the gap perfectly — three runs!",
    "The big man runs hard — three to the total!",
    "Inside-out drive — held up in the wind, three!",
    "Upper cut just short of the ropes — three!",
    "Fantastic placement! Three to the batter!",
    "Muscled to deep midwicket — three runs! Incredible running!",
    "Slog sweep to deep square — the fielder cleans up, but it's three!",
    "Down the ground with authority — three!",
    "Hammered to deep cover — three taken with athletic running!",
    "The throw misses! Three runs to the batter!",
    "Cross-batted smash — three! Just fell short of the boundary.",
    "Driven elegantly — three more to this gorgeous innings!",
    "Picked the gap at deep point — three runs!",
    "Pulled with intent — just the three, but impressive!",
    "They turn sharply and get the third! Brilliant between the wickets!",
    "Carved over the infield — three! What execution!",
    "Lofted to long-off — three with superb judgement!",
    "Slashed hard — three to the batter! Good recovery by the fielder.",
    "On-drive to the boundary rope — three only but brilliantly placed!",
    "Hard-earned three! The batter is breathing hard!",
    "What awareness! Three runs with barely a swing!",
    "Deft touch and three taken! Class act!",
    "Muscled off the back foot — three to deep point!",
    "Slow outfield helps — three runs!",
    "Nudged to the leg side — three with brilliant running!",
    "Straight drive, not quite to the boundary — three!",
    "Heaved to long-on — three runs!",
    "Late cut flies — three to the deep!",
    "Sweet strike! Three but it deserved four!",
    "Almost a boundary! Three to this determined batter!",
    "Excellent running makes it three! Athletic display!",
    "Power and placement combine — three runs!",
    "Cracked past the diving fielder — three!",
    "Hard-running three! Both batters giving it everything!",
    "Three more! The scoreboard accelerates!",
  ],
  "4": [
    "FOUR! Cracked to the boundary! 🔥",
    "BOUNDARY! That's racing away!",
    "Smashed for FOUR! What a shot!",
    "Four runs! The crowd goes wild!",
    "That's a classic FOUR! Textbook timing.",
    "FOUR! Through the covers like a bullet!",
    "Boundary! Pulled with authority!",
    "FOUR MORE! Unstoppable today!",
    "Sweetly timed — races to the fence!",
    "FOUR! Carved over the slips! Brave!",
    "That's raced away! FOUR! 🔥",
    "Dispatched to the boundary! Four!",
    "Crashing FOUR! What timing!",
    "FOUR! Swept with disdain!",
    "Glorious cover drive for FOUR!",
    "Cut shot! FOUR! Brutal hitting!",
    "Late cut — FOUR to third man!",
    "FOUR! Straight down the ground!",
    "Flicked off the pads — FOUR! Class!",
    "BOUNDARY! That was absolutely creamed! 🔥",
    "FOUR! Effortless timing from the batter!",
    "That is pure class! Driven for FOUR!",
    "BOUNDARY! The bowler has nowhere to hide!",
    "FOUR! Uppercut over point — magnificent!",
    "Punched through the covers — FOUR! Stunning!",
    "Back foot cover drive — FOUR! What a sight!",
    "FOUR! Pulled in front of square with venom!",
    "Inside-out FOUR over extra cover! Brilliant shot!",
    "Reverse swept for FOUR! Innovation at its best!",
    "FOUR! Paddle sweep right off the face! Genius!",
    "Hammered through midwicket — FOUR! Power cricket!",
    "FOUR! The ball kissed the boundary rope!",
    "Sent to the boundary with a thunderous drive! FOUR!",
    "FOUR! That's gone through the keeper's legs! Drama!",
    "On-drive for FOUR! The bowler shakes his head!",
    "Square drive for FOUR! Text-book batting!",
    "FOUR! Lofted just over the infield — perfectly placed!",
    "Whipped off the pads — FOUR! The crowd erupts!",
    "Late cut with surgical precision — FOUR!",
    "FOUR! That shot had eyes! Found the gap perfectly!",
    "Step out and drive — FOUR! No fear whatsoever!",
    "FOUR! Absolutely creamed through point!",
    "Swept with immense power — FOUR! 🔥",
    "FOUR! The fielder didn't even move! That was too fast!",
    "Nailed through the covers — racing away for FOUR!",
    "FOUR! The bat swung like a sword! Pure aggression!",
    "Caressed to the boundary — FOUR! Silky smooth!",
    "FOUR! Off the back foot, over the slips! Bold!",
    "Pull shot! FOUR! That was hit with controlled fury!",
    "FOUR! Picked the length early and dispatched it!",
    "Driven with the full face — FOUR runs!",
    "FOUR! First boundary of the over! The pressure releases!",
    "Short ball demolished — FOUR! Upper cut heaven!",
    "FOUR! Down the ground with majestic power!",
    "Cover driven for FOUR! This is batting poetry!",
    "FOUR! Through point like a tracer bullet!",
    "The ball screams to the fence — FOUR!",
    "Picture-perfect straight drive — FOUR! 🔥",
    "Inside edge beats the stumps — FOUR! Lucky but they all count!",
    "FOUR! This batter is in imperious form tonight!",
  ],
  "6": [
    "SIX! Massive hit! That's out of the ground! 🚀",
    "MAXIMUM! What a strike!",
    "SIX! Into the stands! Unbelievable power!",
    "That's a SIX! Absolutely dispatched!",
    "HUGE SIX! The ball has disappeared!",
    "SIX! Monster hit! Into orbit! 🚀",
    "That's gone all the way! MAXIMUM!",
    "SIX! What a majestic strike!",
    "Into the crowd! SIX! Sensational!",
    "Launched over long-on — SIX! 🚀",
    "SIX! Demolished that bowling!",
    "Out of the stadium! MAXIMUM!",
    "SIX! Scooped over the keeper! Audacious!",
    "Flat batted for SIX! Incredible power!",
    "That's in the upper tier! MAXIMUM! 🚀",
    "SIX! Reverse swept into next week!",
    "Helicoptered for SIX! Vintage!",
    "SIX! Clean as you like! Pure muscle!",
    "Deposited into Row Z! MAXIMUM! 🚀",
    "SIX! Standing ovation time! What a hit!",
    "SIX! That ball has left the building! Absolutely mammoth!",
    "MAXIMUM! Pure brute force! The crowd can't believe it!",
    "SIX! Picked it up from outside off and launched it into the night sky!",
    "Into the second tier! SIX! How far did that go?! 🚀",
    "SIX! Stepped out and murdered that delivery! No mercy!",
    "That's a monstrous SIX! The bat sounded like thunder!",
    "MAXIMUM! Over long-on, over the stands, into the parking lot!",
    "SIX! Slog sweep with unbelievable timing and power!",
    "Into the stands at deep midwicket — SIX! What a player!",
    "SIX! The bowler is shell-shocked! That was dispatched!",
    "One-handed SIX! Audacious! The crowd goes absolutely bonkers! 🚀",
    "That's sailed over the ropes! MAXIMUM! Incredible hitting!",
    "SIX! Down the ground like a missile! Can't stop that!",
    "Picked it up on the rise — SIX! Outrageous shot!",
    "SIX! Upper-cut over third man! Don't see that every day!",
    "Launched into orbit! The ball needs a passport! MAXIMUM! 🚀",
    "SIX! Absolutely pulverized that delivery! Carnage!",
    "Over cow corner for SIX! Raw, unadulterated power!",
    "Switch hit for SIX! Innovation meets devastation!",
    "MAXIMUM! Cleared the boundary with yards to spare!",
    "SIX! That's been hit so hard it's still rising!",
    "Inside out over extra cover — SIX! What skill!",
    "SIX! The commentators are running out of words! Spectacular!",
    "Deposited into the crowd! SIX! Fan souvenir incoming!",
    "MAXIMUM! The bowler wants to hide! That was merciless!",
    "SIX! Walk down the pitch, swing of the bat, ball gone! Simple!",
    "Scooped for SIX! How creative! How daring! 🚀",
    "SIX! That's vintage power hitting! The scoreboard explodes!",
    "Over deep square leg! SIX! That's left the stratosphere!",
    "SIX! The bat came down like a hammer! Devastating blow!",
    "Into the cheap seats! MAXIMUM! This batter means business!",
    "SIX! Straight as an arrow, over the bowler's head! Poetry!",
    "Flat SIX over mid-off! Didn't even look up! Ice cold! 🚀",
    "SIX! That sailed so high, planes had to wait!",
    "MAXIMUM! Picked the slower one and still sent it to orbit!",
    "SIX! Two in a row?! This batter is on FIRE!",
    "Clean strike for SIX! The sound of leather on willow was glorious!",
    "SIX! Standing ovation from both dugouts! Even the opposition claps!",
    "MAXIMUM! That's the shot of the tournament! Incredible! 🚀",
    "SIX! Helicopter shot! The wrists do all the work! Magnificent!",
  ],
};

const BOWLING_RUNS: Record<string, string[]> = {
  "0": [
    "Dot ball! Tight bowling.",
    "No runs conceded — well bowled!",
    "Defence from the AI. No damage.",
    "AI can't score off that! Dot ball.",
    "Brilliant line and length — zero!",
    "Strangled for runs! Dot ball.",
    "AI beaten! No run scored.",
    "Misses completely — dot ball!",
    "You've tied them down! Zero runs.",
    "Pressure bowling! Another dot.",
    "AI blocked it dead. No run.",
    "Right on target — dot ball!",
    "That's an unplayable delivery! Zero.",
    "Maiden territory! Another dot.",
    "Suffocating spell — dot ball!",
    "AI plays and misses! No run.",
    "Line and length perfection — dot!",
    "Defensive prod — zero runs conceded.",
    "Building pressure! Another dot ball.",
    "AI has no answer! Dot ball.",
    "Stifled! The AI can't get it away. Dot.",
    "Beaten outside off! Another dot. You're on fire!",
    "AI defends cautiously. Zero runs conceded.",
    "Pin-point accuracy! Dot ball.",
    "AI survives but can't score. Dot.",
    "Another brilliant dot! The pressure mounts!",
    "The AI is struggling here! Dot ball.",
    "On the money! Can't score off that. Zero.",
    "Cramped for room — AI can't free the arms. Dot.",
    "Tremendous bowling spell! Another dot ball.",
    "AI beaten all ends up! Dot! What a delivery!",
    "You're bowling a masterclass! Another zero.",
    "Full and straight — AI blocks. No run.",
    "Short of a length — AI ducks. Dot ball.",
    "Slower ball bamboozles the AI! Zero runs!",
    "AI plays inside the line — dot ball.",
    "Nipping back into the pads — AI defends. Dot.",
    "Outside off, AI leaves alone. Smart, but still a dot.",
    "Yorker length! AI digs it out. No run.",
    "AI misjudges the length — dot ball!",
    "Bouncer! AI sways out of the way. Dot.",
    "Seam movement! AI edges but misses. Dot ball!",
    "Full toss wasted by the AI — blocks it. Dot.",
    "You're in the zone! Another dot. Keep going!",
    "Peach of a delivery! AI barely survives. Zero.",
    "The AI is pinned down! Dot ball.",
    "Probing line outside off — AI leaves. Dot.",
    "AI stuck on the crease — dot ball!",
    "Beautiful bowling! AI can't rotate strike.",
    "Tight, disciplined, and rewarding — another dot!",
    "You've got the AI in trouble! Zero off that one.",
    "Back of a length, cramping the AI. Dot ball.",
    "Slower delivery confuses the AI! Dot!",
    "Off-cutter! AI beaten. Dot ball.",
    "AI swings and misses! No run. You're dominating!",
    "Unplayable! AI survives but can't score.",
    "Full and swinging — AI defends. Zero.",
    "AI lunges forward — dot ball!",
    "You're making this look easy! Another dot.",
    "Relentless pressure! Dot ball number who-knows-what!",
  ],
  "1": [
    "AI takes a single.",
    "One run to the opposition.",
    "AI nudges one — stay focused!",
    "Single conceded. Keep it tight.",
    "AI rotates strike — just one.",
    "One run leaked. Not much damage.",
    "AI works it for a single.",
    "Quick single to the AI. Stay sharp.",
    "Just the one conceded there.",
    "AI steals a single off the pads.",
    "Pushed for one by the AI.",
    "One run — the AI ticks along.",
    "Dabbed away for a single. Minor.",
    "AI picks up one off that delivery.",
    "Single taken — no big deal.",
    "AI finds a gap for one.",
    "One off the edge — lucky single.",
    "AI clips it away for a single.",
    "Soft single to the AI.",
    "One run conceded off the pads.",
    "AI rotates strike. Just a single, you're still in control.",
    "Nudged to leg — one run. Don't worry about it.",
    "AI clips it for one. Minimal damage.",
    "Inside edge and a single. Could have been worse!",
    "AI opens the face for a single to third man.",
    "Tapped to point — AI scurries through for one.",
    "One run leaked down the leg side.",
    "AI glances it fine — single taken.",
    "Decent delivery but AI manages a single.",
    "One more to the AI. Stay patient!",
    "AI flicks it off the hip — single.",
    "Pushed to mid-off — AI takes a quick one.",
    "Good delivery but AI squeezes out a single.",
    "AI drops it at his feet — steals a single!",
    "Leg stump half-volley — AI flicks for one.",
    "AI guides it to gully for a single.",
    "One to the off side. AI ticking along.",
    "Turn and bounce — but AI gets a single anyway.",
    "AI works it behind square for one.",
    "Short ball — AI ducks and takes a single off the next.",
    "AI defending well — picks up a single here.",
    "One run to deep fine leg. Acceptable.",
    "AI uses the pace — guides it for a single.",
    "Tucked off the hip — one to the AI.",
    "One more to the total. Keep your head up!",
    "AI punches it gently — single to cover.",
    "Loopy delivery — AI pushes for one.",
    "AI chips it safely — just a single.",
    "Tight single to the AI. Close run-out chance!",
    "AI squirts it to point — takes a quick one.",
    "Edge and one! Could have been caught!",
    "AI survives and gets a single. Frustrating!",
    "Off the pad for a lucky single to AI.",
    "Good bounce — AI fends for a single.",
    "AI sweeps — single to fine leg.",
    "Late cut by AI — just the one.",
    "AI dabs to third man for a single.",
    "One run — AI keeps the scoreboard moving.",
    "AI prods forward — single to mid-on.",
    "That was almost a dot! AI sneaks a single.",
  ],
  "2": [
    "AI finds two. Pressure building.",
    "Two runs conceded.",
    "AI pushes through for two!",
    "Two to the AI — tighten up!",
    "AI splits the field — two runs.",
    "Two more to the AI's total.",
    "Gap found by AI — two taken.",
    "AI runs hard — two scored.",
    "Driven for two by the AI.",
    "Two runs leak away there.",
    "AI threads it through — two!",
    "Quick two to the AI. Careful!",
    "AI gets two — scoring accelerating.",
    "Two runs! AI finding rhythm.",
    "Placed well by AI — two taken.",
    "AI steals two with quick running.",
    "Two conceded through the covers.",
    "AI works it square for two.",
    "Two more — AI looks comfortable.",
    "AI punches it for a brace.",
    "Two runs! AI is starting to time the ball well.",
    "Good running by the AI — two scored!",
    "AI places it wide of mid-on — two runs!",
    "Swept for two by the AI. Not ideal.",
    "AI cracks it through point — two taken!",
    "Two more! The AI is finding gaps now.",
    "AI drives down the ground — comfortable two.",
    "Cut shot by the AI — two to the rope!",
    "Two runs! AI looking more settled.",
    "AI clips off the pads — two runs. Tighten up!",
    "AI finds the gap at cover — two!",
    "Pulled to deep square — AI takes two!",
    "Two more to the AI. Need to stem the flow!",
    "AI steps out and lofts — two runs only. Close!",
    "AI works it behind square — two taken.",
    "Two to the AI through midwicket!",
    "Controlled shot by AI — two runs scored.",
    "AI whips it to deep — two with good running.",
    "Two more leaked. The AI is building momentum!",
    "AI threads the gap perfectly — two runs!",
    "Push and run — AI gets two!",
    "AI opens the face — two to third man!",
    "Hard-run two by the AI. Athletic display.",
    "AI on-drives for two! Getting into a groove.",
    "Two conceded through midwicket. Need a change!",
    "AI glances — two taken with smart running.",
    "Placed between fielders — two to the AI!",
    "AI feathers it fine — two runs!",
    "Two more! AI rotating strike well.",
    "AI punches off the back foot — two!",
    "Straight drive by AI — two to long-off!",
    "AI lofts safely — just the two.",
    "Two runs to AI down the ground!",
    "AI flicks it handsomely — two runs.",
    "Late cut by AI — two to third man!",
    "AI drives — two more to the total!",
    "Guided past gully — two to AI!",
    "AI capitalizes on the loose ball — two!",
    "Cross-bat smash — two to deep!",
    "AI picking gaps at will — two more!",
  ],
  "3": [
    "Three to the AI. Stay focused!",
    "Three runs — AI finding gaps.",
    "AI races through for three!",
    "Three conceded! Boundary saved at least.",
    "AI hammers it — three runs!",
    "Three to the AI — getting expensive.",
    "Good shot by AI — three taken.",
    "AI threads three through the field!",
    "Three more to the AI. Pressure!",
    "AI drives for three — ouch!",
    "Fielder can't cut it off — three!",
    "Three runs by the AI. Need a wicket!",
    "AI picks three — scoring rate up.",
    "Expensive delivery! Three to the AI.",
    "AI cracks it for three runs.",
    "Three! AI looking dangerous now.",
    "Run hard by the AI — three scored.",
    "Three more leaked. Bowl tighter!",
    "AI places it expertly — three!",
    "Three runs — AI in control.",
    "Three to the AI! That delivery was too short!",
    "AI muscles it to deep midwicket — three runs!",
    "Three conceded! The AI is timing everything now.",
    "Drilled to the deep — three to the AI!",
    "AI launches but it falls short — three runs!",
    "Three more! The AI run rate is climbing!",
    "AI picks the gap expertly — three taken!",
    "Pulled to deep square — three to the AI!",
    "Three runs! The outfielder can't get there in time!",
    "AI drives on the up — three! Classy shot!",
    "Three conceded off a misfield. Frustrating!",
    "AI clips it fine — three with athletic running!",
    "Hammered down the ground — three to AI!",
    "Three! The AI found the only gap!",
    "Whipped to deep — three runs to the AI.",
    "AI upper cuts — three! That was brave!",
    "Three more! AI building a big score here.",
    "Lofted to the deep — three to the AI!",
    "AI threads it past the diving fielder — three!",
    "Three! Misfield at cover gifts the AI extra runs.",
    "AI slog sweeps — three! Fortunate it didn't carry.",
    "Three to the AI off a full toss. Bad ball!",
    "AI crashes it through covers — three runs!",
    "Three! AI taking toll of the bowling.",
    "Driven imperiously — three to the AI!",
    "AI edges — three! Lucky runs there.",
    "Three runs to deep point! AI exploiting the gaps.",
    "Controlled slog for three by the AI!",
    "AI whips it behind square — three!",
    "Three more leaked! Time for a bowling change?",
    "AI pounces on the loose delivery — three!",
    "Carved past gully — three to the AI!",
    "AI goes aerial — three! Didn't quite carry.",
    "Three conceded via the leg side. Change the angle!",
    "AI works it square — three runs!",
    "Hard-running three by the AI. They're hungry!",
    "AI finds the deep — three taken!",
    "Three! AI looking ominous now.",
    "Pulled powerfully — three to the AI!",
    "Three more! This is getting away from you!",
  ],
  "4": [
    "FOUR conceded! AI finding boundaries.",
    "Boundary! AI hits four. Tighten up!",
    "FOUR! AI cracks it to the fence!",
    "Boundary off the AI bat — four runs!",
    "AI smashes four! Getting tough.",
    "FOUR! AI punishes the loose ball!",
    "Racing to the boundary — four to AI!",
    "AI drives it for FOUR! Costly!",
    "Boundary again! AI on the attack.",
    "FOUR! AI is in the zone now!",
    "Dispatched for four by the AI!",
    "AI carves it away — FOUR!",
    "Four more! AI piling on runs.",
    "FOUR! AI finds the gap perfectly.",
    "AI pulls it for FOUR! Need answers.",
    "Crashed through covers — FOUR to AI!",
    "AI cuts for FOUR! Change it up!",
    "Four conceded — AI accelerating.",
    "FOUR! AI is batting beautifully.",
    "Swept for four! AI dominant.",
    "FOUR! AI drives through the covers with authority!",
    "Boundary to the AI! That was a bad ball and it was punished!",
    "AI sends it racing to the fence! FOUR!",
    "FOUR! AI pulled with disdain! Change your line!",
    "AI lofts over mid-off — FOUR! Fearless batting!",
    "FOUR! AI flicks off the pads! Sweet timing!",
    "Through the gap! FOUR to the AI! You need a plan!",
    "AI reverse sweeps for FOUR! Cheeky!",
    "FOUR! AI hammers a pull shot! Ouch!",
    "Boundary! AI cuts hard past point — FOUR!",
    "AI on-drives for FOUR! That was clinical!",
    "FOUR! Full toss dispatched by the AI!",
    "AI upper cuts for FOUR over the slips!",
    "FOUR! AI sweeps with conviction!",
    "Driven straight for FOUR by the AI! Top batting.",
    "FOUR! AI inside edges past the keeper! Lucky!",
    "AI late cuts for FOUR! Delicate but effective!",
    "Boundary! AI steps out and crashes it through cover!",
    "FOUR! AI punches off the back foot — no stopping that!",
    "AI whips it through midwicket — FOUR! Power!",
    "FOUR to the AI! You're bleeding runs here!",
    "AI creams it to the boundary! FOUR! Dominant batting.",
    "FOUR! AI picks the gap with ease!",
    "Crashed through point — FOUR to the AI! Need a wicket badly!",
    "AI paddle scoops for FOUR! Innovative!",
    "FOUR! AI muscles it over mid-on! Strong batting!",
    "AI sends it screaming to the fence — FOUR!",
    "FOUR! Short and wide — AI cuts it away!",
    "Boundary to the AI off a no-ball too! FOUR! Double whammy!",
    "AI cracks it through extra cover — FOUR! Text-book!",
    "FOUR! AI is demolishing this bowling attack!",
    "AI drives on the up — FOUR! Exquisite shot!",
    "FOUR! Pulled in front of square — the AI is in cruise control!",
    "AI flicks it behind square — FOUR! Too easy!",
    "FOUR to the AI through midwicket! Change it up!",
    "Full and wide — AI drives for FOUR! Free hit!",
    "AI smashes it straight back — FOUR! The bowler ducks!",
    "Edge and FOUR! AI gets lucky there!",
    "Cover driven for FOUR! AI at its best.",
    "FOUR! AI times it beautifully off the back foot!",
  ],
  "6": [
    "SIX to the AI! Big hit from the opposition!",
    "MAXIMUM by AI! Need to bowl tighter!",
    "SIX! AI launches it into orbit!",
    "AI smashes a massive SIX! Trouble!",
    "Gone for SIX! AI is on fire!",
    "MAXIMUM! AI takes it downtown!",
    "SIX conceded! That hurt!",
    "AI deposits it for SIX! Ouch!",
    "Out of the ground! SIX to the AI!",
    "AI muscles it for MAXIMUM!",
    "SIX! AI clearing the boundaries easily!",
    "Hammered for SIX by the AI!",
    "AI goes aerial — SIX! Need a plan.",
    "MAXIMUM! AI is unstoppable right now!",
    "SIX! AI doesn't hold back!",
    "Into the stands! SIX by the AI!",
    "Monster SIX from the AI. Regroup!",
    "AI launches for SIX — devastating!",
    "SIX! The AI means business!",
    "MAXIMUM from AI! Total carnage!",
    "SIX to the AI! That ball has left the postcode!",
    "MAXIMUM! AI stepped out and murdered that ball!",
    "SIX! AI sends it into the cheap seats!",
    "Massive SIX! The AI isn't showing any respect! Regroup!",
    "AI launches it over long-on — SIX! Monster hit!",
    "SIX! AI clears the rope with ease! You need to bowl yorkers!",
    "MAXIMUM! AI slog sweeps for SIX! That was powerful!",
    "SIX! The AI picked the length early and dispatched it!",
    "Hammered down the ground — SIX to the AI! What a shot!",
    "SIX! AI shows incredible power! The crowd cheers!",
    "Into the second tier! SIX by the AI! Incredible hitting!",
    "AI flat bats it for SIX! Can't bowl there!",
    "MAXIMUM! AI reverse sweeps for SIX! Outrageous!",
    "SIX! AI picks it up off the toes! Wristy!",
    "AI deposits it for SIX! This is getting out of hand!",
    "SIX! AI clears cow corner with contempt!",
    "MAXIMUM to the AI! The bowling is under siege!",
    "SIX! AI upper cuts over third man! Brave shot!",
    "AI switches and reverse hits for SIX! Brilliant!",
    "SIX! AI is on a rampage! Need to contain this!",
    "Crashed over midwicket — SIX! AI dominating!",
    "SIX to the AI! Full toss punished! Bowl fuller!",
    "MAXIMUM! AI heaves it over the leg side!",
    "SIX! AI clubs it straight! No mercy!",
    "Into the stands! MAXIMUM by the AI! Total onslaught!",
    "AI scoops for SIX! Innovation from the opposition!",
    "SIX! AI steps down and launches it effortlessly!",
    "MAXIMUM! AI tonks it over long-off! Devastating!",
    "SIX! The AI is in demolition mode!",
    "AI muscles another SIX! You need a miracle now!",
    "SIX! Picked up from outside off and deposited over long-on!",
    "MAXIMUM! AI swings with all its might — SIX!",
    "SIX! That has gone over everything! Massive hit by AI!",
    "AI goes deep — SIX! The bowler is clueless!",
    "SIX! Switch hit by the AI! Genius cricket!",
    "MAXIMUM! AI absolutely clobbers that one!",
    "Into orbit! SIX to the AI! They're unstoppable!",
    "SIX! AI sends it over the sightscreen!",
    "AI smashes a flat SIX! Raw power!",
    "MAXIMUM! The AI is putting on a show! SIX more!",
  ],
};

const OUT_BATTING = [
  "OUT! Caught matching moves! 💀",
  "WICKET! Identical moves — that's OUT!",
  "Gone! Both played the same — dismissed!",
  "OUT! The innings comes to an end!",
  "Matching moves — OUT! Heartbreak! 💀",
  "Can you believe it? OUT!",
  "Same choice! That's the end — OUT!",
  "DISMISSED! What a cruel way to go!",
  "OUT! Lightning strikes! Both picked the same!",
  "Gone! Trapped by the AI — OUT! 💀",
  "WICKET! Mirror image — you're out!",
  "OUT! The AI read your mind!",
  "Disaster! Same move — OUT!",
  "OUT! That's a painful dismissal!",
  "GONE! AI matches perfectly — wicket! 💀",
  "OUT! The stumps are shattered!",
  "Edged and caught — same move! OUT!",
  "OUT! Walk back to the pavilion!",
  "BOWLED! Matching moves — OUT! 💀",
  "That's the killer blow — OUT!",
  "OUT! The AI saw that coming a mile away! 💀",
  "DISMISSED! You walked right into that trap!",
  "OUT! The crowd falls silent... heartbreaking!",
  "GONE! Same number — same fate! OUT! 💀",
  "OUT! Not the ending you wanted! Back to the dugout!",
  "WICKET! The AI celebrates! Matching moves — dismissed!",
  "OUT! What a cruel twist of fate! Both chose identically!",
  "GONE! The AI has won that battle! OUT!",
  "OUT! Unbelievable! Read like a book! 💀",
  "DISMISSED! The AI predicted that perfectly!",
  "OUT! That's the end of a promising innings!",
  "GONE! Both minds thought alike — OUT! 💀",
  "OUT! Into the pavilion you go! Tough luck!",
  "WICKET! The AI's mind-reading powers strike! OUT!",
  "OUT! Devastating! The innings crashes to a halt! 💀",
  "DISMISSED! Same choice, game over for you!",
  "OUT! The AI strikes at the worst possible time!",
  "GONE! Matched up — and that means OUT! 💀",
  "OUT! Dreams shattered! The AI triumphs on that ball!",
  "WICKET! Oh the agony! Both played the same number!",
  "OUT! What a way to go! Cruel cricket! 💀",
  "DISMISSED! The AI had your number — literally!",
  "OUT! Painful end to a fighting innings!",
  "GONE! The AI strikes gold! Matching moves — OUT!",
  "OUT! The stumps are rattled! Same number — dismissed! 💀",
  "WICKET! The AI's spell works! OUT!",
  "OUT! A moment of genius from the AI! Or bad luck for you!",
  "DISMISSED! Mirror, mirror — you're OUT! 💀",
  "OUT! The crowd gasps! Same move means dismissal!",
  "GONE! Like ships in the night — same choice, OUT!",
  "OUT! The AI pounces! Matching numbers — wicket! 💀",
  "DISMISSED! Gutted! Both on the same wavelength!",
  "OUT! Telepathic AI! You're walking! 💀",
  "GONE! The innings ends with a cruel twist!",
  "OUT! You can't believe it! Same move, same outcome — dismissed!",
  "WICKET! The AI claims another victim! OUT! 💀",
  "OUT! Heartbreaker! Matching moves seal your fate!",
  "DISMISSED! The perfect trap! The AI gets you! 💀",
  "OUT! That's the dagger! Matching moves — innings over!",
  "GONE! The AI celebrates — you're walking back! OUT! 💀",
];

const OUT_BOWLING = [
  "WICKET! AI is OUT! Great bowling! 🎯",
  "Got 'em! AI dismissed with matching moves!",
  "BOWLED! AI plays the same — OUT!",
  "What a delivery! AI is gone!",
  "WICKET! AI falls! Brilliant! 🎯",
  "AI is OUT! Same move — beautiful!",
  "Trapped! AI dismissed — celebration time! 🎯",
  "OUT! AI walks back. What a moment!",
  "WICKET! You've outsmarted the AI!",
  "AI is GONE! Matching moves — dismissed!",
  "YOU GOT THE WICKET! AI out! 🎯",
  "What a catch! AI out on matching!",
  "CLEANED UP! AI dismissed — OUT!",
  "AI departs! Same move — wicket!",
  "OUT! AI has no answer for that! 🎯",
  "Stumps flying! AI is OUT!",
  "BRILLIANT bowling! AI dismissed!",
  "The AI crumbles — OUT! 🎯",
  "WICKET! Mirror move — AI is done!",
  "AI gone for good! What a spell! 🎯",
  "WICKET! You've cracked the code! AI dismissed! 🎯",
  "OUT! The AI couldn't escape that trap! Brilliant!",
  "GONE! AI walks back in disbelief! YOU did it! 🎯",
  "WICKET! Same number — AI is OUT! What a moment!",
  "AI is DONE! Matching moves seal the deal! 🎯",
  "OUT! You read the AI like a book! Dismissed!",
  "WICKET! The AI falls to your genius! 🎯",
  "BOWLED HIM! AI played the same number — OUT!",
  "AI departs! Your bowling is sensational! WICKET! 🎯",
  "OUT! The AI never saw it coming! Brilliant trap!",
  "GONE! AI matched your move and pays the price! 🎯",
  "WICKET! Celebrations all around! AI is OUT!",
  "OUT! You've broken through! AI dismissed! 🎯",
  "The AI crumbles under pressure — OUT! What a spell!",
  "WICKET! Perfect strategy! AI falls! 🎯",
  "AI is HISTORY! Same move — you claim the wicket!",
  "OUT! Pumping fists! AI walks! 🎯",
  "DISMISSED! The AI's resistance ends! Matching moves!",
  "WICKET! The stumps are shattered! AI OUT! 🎯",
  "OUT! You've done it again! AI dismissed!",
  "GONE! AI couldn't solve you! Wicket! 🎯",
  "CLEAN BOWLED! AI plays the same — OUT!",
  "WICKET! What a spell! AI has no answer! 🎯",
  "OUT! The crowd erupts! AI dismissed with style!",
  "AI falls! Matching moves — you get the prize! 🎯",
  "WICKET! Poetry in motion! AI is OUT!",
  "OUT! You outsmarted the machine! Brilliant! 🎯",
  "DISMISSED! The AI walks, head down! You celebrate!",
  "WICKET! Same number, different outcomes — AI OUT! 🎯",
  "OUT! The tables have turned! AI crumbles!",
  "GONE! You've dismantled the AI's innings! 🎯",
  "WICKET! Timing, strategy, and the matching move! OUT!",
  "AI is BOWLED! You couldn't have planned it better! 🎯",
  "OUT! The AI's nightmare! Matching moves — dismissed!",
  "WICKET! Chef's kiss! AI departs! Beautiful bowling! 🎯",
  "OUT! Mind games won! AI matched and lost!",
  "GONE! AI's innings ends in matching misery! 🎯",
  "WICKET! A master bowler at work! AI OUT!",
  "AI DISMISSED! That's a screamer of a wicket! 🎯",
  "OUT! The AI's run is over! Fabulous bowling! 🎯",
];

const WIN_COMMENTS = [
  "🏆 CHAMPION! What a performance!",
  "🏆 VICTORY! You've conquered the AI!",
  "🏆 MATCH WON! A masterclass!",
  "🏆 INCREDIBLE WIN! Standing ovation!",
  "🏆 Glory! You've won the match!",
  "🏆 What a triumph! Victory is yours!",
  "🏆 Unbeatable! You've done it!",
  "🏆 CHAMPION performance! Take a bow!",
  "🏆 Sensational win! Cricket genius!",
  "🏆 The trophy is yours! What a match!",
  "🏆 WINNER! The crowd erupts!",
  "🏆 Dominated! Complete victory!",
  "🏆 Historic win! One for the ages!",
  "🏆 MATCH WON! Pure brilliance!",
  "🏆 Unstoppable! A famous victory!",
  "🏆 Conquered the AI! You're legendary!",
  "🏆 Total domination! Champion!",
  "🏆 The stadium goes wild! YOU WIN!",
  "🏆 Clinical victory! Absolute perfection!",
  "🏆 EPIC WIN! You've made history!",
  "🏆 What a player! Victory sealed with class!",
  "🏆 The AI bows down! YOU are the champion!",
  "🏆 Flawless! A victory that'll be remembered forever!",
  "🏆 The crowd chants your name! WINNER!",
  "🏆 Demolished the AI! What a statement victory!",
  "🏆 That's how it's done! Clinical finish!",
  "🏆 The AI has been outplayed, outclassed, outmatched!",
  "🏆 Victory! Your fans are going crazy right now!",
  "🏆 A win for the history books! Absolutely magnificent!",
  "🏆 Champion mentality! You never doubted yourself!",
  "🏆 The stadium erupts! Confetti rains down! YOU WIN!",
  "🏆 From the first ball to the last — dominance!",
  "🏆 The AI was no match today! Complete victory!",
  "🏆 You showed up and showed out! WINNER!",
  "🏆 Nerves of steel! A champion's finish!",
  "🏆 Take a bow, champion! What a display!",
  "🏆 The AI has been humbled! Victory is sweet!",
  "🏆 Every shot, every decision — perfection! YOU WIN!",
  "🏆 Game, set, match! Victory sealed beautifully!",
  "🏆 The legend grows! Another win to the trophy cabinet!",
  "🏆 Extraordinary performance! The AI never stood a chance!",
  "🏆 WON IT! The journey was tough but the result is glorious!",
  "🏆 A tactical masterclass! The AI had no answers!",
  "🏆 Winning under pressure — that's what champions do!",
  "🏆 The crowd gives a standing ovation! VICTORY!",
  "🏆 You've etched your name in glory! Champion!",
  "🏆 From zero to hero! What a comeback victory!",
  "🏆 The AI crumbled! Your victory is complete!",
  "🏆 Celebrate! You've earned every bit of this win!",
  "🏆 Lights, camera, VICTORY! What a show!",
  "🏆 Supreme confidence! Supreme victory!",
  "🏆 The ultimate prize! You've won it all!",
  "🏆 Not even close! Total domination!",
  "🏆 The AI needs to practice more! VICTORY!",
  "🏆 Ice cold finish! Champion material right there!",
  "🏆 WON IT IN STYLE! What a way to cap off the match!",
  "🏆 The sweetest victory! Savour every moment!",
  "🏆 Incredible composure under pressure — YOU WIN!",
  "🏆 History is made! Another glorious victory!",
  "🏆 A performance of pure genius! CHAMPION!",
];

const LOSS_COMMENTS = [
  "AI takes the match. Better luck next time!",
  "Defeated by the AI. Regroup and try again!",
  "Close match, but AI edges it.",
  "AI prevails. Don't give up!",
  "Tough loss. AI was too strong today.",
  "AI clinches the win. Try a rematch!",
  "Not this time. AI takes the honors.",
  "AI wins! Shake it off and come back!",
  "Heartbreak! AI steals the match.",
  "AI triumphs. The fight continues!",
  "Narrow defeat. You'll get 'em next time!",
  "AI claims victory. Stay resilient!",
  "Lost this battle, not the war!",
  "AI wins the day. Regroup, champion!",
  "So close! AI just edges past you.",
  "AI takes the spoils today.",
  "Defeated, but you fought well!",
  "AI wins — time for a revenge match!",
  "Tough result. Learn and come back stronger!",
  "AI stands victorious. Next time is yours!",
  "The AI outplayed you today. But tomorrow is a new day!",
  "Not your day. The AI was just too sharp!",
  "Heartbreaker! AI snatches victory from the jaws of defeat!",
  "AI wins this round. But champions come back stronger!",
  "Tough pill to swallow! AI clinches it at the death!",
  "The AI was relentless today. Regroup and reload!",
  "You gave it everything but the AI was just better. Respect!",
  "Defeat stings, but it builds character. You'll bounce back!",
  "AI takes the W. Time to study the playbook!",
  "Not the result you wanted. Keep grinding!",
  "The AI had the answers today. But the series isn't over!",
  "Close but no cigar! AI edges the thriller!",
  "AI wins, but what a fight you put up!",
  "Disappointing result, but you showed heart!",
  "The AI capitalised on the pressure moments. Learn from this!",
  "AI stands tall. You'll be back, no doubt!",
  "A tough loss but the comeback story starts now!",
  "AI was clinical today. Time to sharpen your game!",
  "Defeated today, determined tomorrow!",
  "The AI celebrated. Let that fuel your fire!",
  "Loss number whatever — but winners never quit!",
  "AI got the better of you. The rematch awaits!",
  "You fought valiantly but AI takes the crown today.",
  "Not your finest hour. But there's always next match!",
  "AI seals it! Disappointment now, determination next!",
  "The loss hurts. Channel it into the next game!",
  "AI outmuscled you today. Hit the training ground!",
  "Couldn't quite get over the line. AI wins!",
  "So close to glory! AI takes it at the wire!",
  "AI proves too strong. The comeback kid rises next time!",
  "Today was the AI's day. Yours is coming!",
  "Tough loss, but the hunger for victory grows!",
  "AI won the match, but you won hearts!",
  "Head high! Even the greatest lose sometimes.",
  "AI's strategy prevailed today. Time for a new plan!",
  "Defeated but not broken. The fire still burns!",
  "AI walks away with the win. Your time will come!",
  "A setback, not a failure. Champions learn!",
  "AI takes the glory today. Tomorrow? That's your day!",
  "Lost the match but gained the experience. Keep going!",
];

const DRAW_COMMENTS = [
  "🤝 A TIE! What a closely fought contest!",
  "🤝 Honors even! Neither side could separate.",
  "🤝 Dead heat! Incredible match!",
  "🤝 A draw! Both teams gave everything!",
  "🤝 Level pegging! What a game!",
  "🤝 Tied up! Neither budges — epic!",
  "🤝 Both sides equal! A fair result.",
  "🤝 Mirror finish! It's a tie!",
  "🤝 Deadlock! What drama!",
  "🤝 All square! A match for the ages!",
  "🤝 Locked together! Perfect balance.",
  "🤝 Neither can separate — it's a draw!",
  "🤝 Even-steven! Remarkable contest!",
  "🤝 A tie! Both deserve to win!",
  "🤝 Stalemate! Incredible sportsmanship!",
  "🤝 Shared honors! What a battle!",
  "🤝 It's level! A thrilling draw!",
  "🤝 Deadlocked! This game had everything!",
  "🤝 Perfectly matched — a tie!",
  "🤝 Split down the middle! Epic draw!",
  "🤝 What a contest! Neither could land the final blow!",
  "🤝 Tied! Both players gave absolutely everything!",
  "🤝 As close as cricket gets! A draw!",
  "🤝 Neither side deserved to lose — and neither did!",
  "🤝 The scores are level! Jaw-dropping finish!",
  "🤝 A DRAW! The crowd is stunned! What a match!",
  "🤝 Evenly matched! This rivalry continues!",
  "🤝 TIE! Same score! Can you believe it?!",
  "🤝 Incredible drama and it ends in a draw!",
  "🤝 Shoulder to shoulder — tied at the finish!",
  "🤝 A draw! But what a match! Pure entertainment!",
  "🤝 Can't separate these two! TIE!",
  "🤝 The cricket gods said 'equal' — and so it is!",
  "🤝 Heart-stopping finish and it's a DRAW!",
  "🤝 Both players collapse — it's a tie! What effort!",
  "🤝 Not a winner between them — TIE!",
  "🤝 Draw! Both fighters exhausted! Respect!",
  "🤝 Level! This match deserves a sequel!",
  "🤝 A tie for the ages! Cricket at its finest!",
  "🤝 Same score! Same glory! Shared honors!",
  "🤝 Neither could finish the other off — DRAW!",
  "🤝 Incredible scenes! The match ends in a tie!",
  "🤝 Dead level! A result that satisfies no one!",
  "🤝 Tied up perfectly! A rematch is mandatory!",
  "🤝 What a cliffhanger — and it ends level!",
  "🤝 Both gave 100% — both get the draw!",
  "🤝 The scores are identical! A fitting end!",
  "🤝 TIE! Run for run, ball for ball — equal!",
  "🤝 A draw that felt like a victory for both!",
  "🤝 Inseparable! Cricket writes its own script!",
  "🤝 Shared the spoils! What a rivalry!",
  "🤝 Not a comma between them — IT'S A TIE!",
  "🤝 A match that had everything — except a winner!",
  "🤝 They played their hearts out — DRAW!",
  "🤝 Joined at the hip! Same score — TIE!",
  "🤝 No one deserved to lose — it's a draw!",
  "🤝 Level pegging at the death! What a thriller!",
  "🤝 A nail-biting draw! Cricket at its dramatic best!",
  "🤝 TIE GAME! The crowd gives a standing ovation!",
  "🤝 How can you separate them?! You can't! DRAW!",
];

const CHASE_COMMENTS = [
  "Getting closer to the target!",
  "The chase is on! Keep going!",
  "Closing in on the target!",
  "Almost there! Keep the focus!",
  "Every run counts in this chase!",
  "The target is within sight!",
  "Chipping away at the target!",
  "Pressure chase — you've got this!",
  "Inching closer with every ball!",
  "Target in range! Keep swinging!",
  "The finish line approaches!",
  "Stay calm, chase it down!",
  "You can smell victory!",
  "Home stretch! Keep going!",
  "The target beckons — push on!",
  "Almost home! Brilliant chase!",
  "One step at a time — closing in!",
  "The run rate is under control!",
  "Target locked! Keep scoring!",
  "The chase heats up! Exciting cricket!",
  "Nibbling away at the target! You've got this!",
  "The required rate is coming down! Great batting!",
  "This chase is going according to plan!",
  "Need to accelerate! The target won't chase itself!",
  "Stay composed! The finish line is near!",
  "The target is shrinking with every ball!",
  "Heart rate rising! The chase intensifies!",
  "Keep your nerve — victory is within reach!",
  "The equation simplifies! Keep going!",
  "A boundary here would change everything!",
  "The AI is sweating — you're closing in!",
  "Victory is in the air! Keep chasing!",
  "Can you feel it? The target is crumbling!",
  "Smart batting! The chase is perfectly on track!",
  "The crowd senses a victory! Chase it down!",
  "Required rate is gettable! Keep calm and score!",
  "This is where legends are made! Chase it!",
  "The finish is so close you can taste it!",
  "Don't let the pressure get to you! Keep scoring!",
  "The AI is on the ropes! Push for the win!",
  "Methodical chase! You're in complete control!",
  "The target melts away! What a chase!",
  "Every ball matters now! Stay focused!",
  "You're in the driver's seat! Chase complete soon!",
  "The momentum is all yours! Keep going!",
  "A few more and it's done! Brilliant!",
  "The equation is simple — just score!",
  "Chase mastery on display! Almost there!",
  "The AI is powerless to stop this chase!",
  "What a chase this is turning out to be!",
  "History beckons! A famous chase awaits!",
  "The crowd roars with every run! Chase on!",
  "Clinical chasing! The target shrinks!",
  "Nerves of steel needed now! You've got them!",
  "The last lap! Victory is one push away!",
  "This chase will be remembered forever!",
  "Required rate dropping! You're cruising!",
  "The AI throws everything — but you keep scoring!",
  "A legendary chase in the making!",
  "One big shot and it could be over! Come on!",
];

// ─── Pre-match commentary scenarios ──────────────────────────────

export const PRE_MATCH_INTROS = [
  (p: string, o: string) => `Welcome to this electrifying showdown! ${p} takes on ${o}! The stadium is buzzing with excitement!`,
  (p: string, o: string) => `It's game day! ${p} versus ${o}! Two fierce competitors ready to battle! Who will emerge victorious?`,
  (p: string, o: string) => `The crowd is on their feet! ${p} faces ${o} in what promises to be an absolute cracker of a match!`,
  (p: string, o: string) => `Ladies and gentlemen, welcome! ${p} and ${o} lock horns today! The atmosphere is electric!`,
  (p: string, o: string) => `The stadium lights are blazing! ${p} versus ${o}! Let the battle commence!`,
  (p: string, o: string) => `What a day for cricket! ${p} against ${o}! Both players are fired up and ready to go!`,
  (p: string, o: string) => `The stage is set! ${p} and ${o} walk onto the pitch! This is going to be special!`,
  (p: string, o: string) => `Anticipation fills the air! ${p} takes on ${o}! The fans can't wait!`,
  (p: string, o: string) => `Here we go! ${p} versus ${o}! The biggest match of the day!`,
  (p: string, o: string) => `The rivalry continues! ${p} meets ${o}! Who has the edge today? Let's find out!`,
];

export const PRE_MATCH_RIVALRY = {
  leading: [
    (p: string, o: string, w: number, l: number) => `${p} leads the head-to-head ${w} to ${l}! The pressure is on ${o} to turn it around!`,
    (p: string, o: string, w: number, l: number) => `${p} has been dominant with ${w} wins against ${o}'s ${l}! Can that dominance continue?`,
    (p: string, _o: string, w: number) => `${p} has won ${w} of their encounters! Confidence should be sky high!`,
    (p: string, o: string, w: number, l: number) => `The record favors ${p}! ${w} victories to ${l} for ${o}! But form is temporary, class is permanent!`,
    (p: string, o: string) => `${p} has the psychological edge over ${o}! The head-to-head says it all!`,
  ],
  trailing: [
    (p: string, o: string, w: number, l: number) => `${o} leads ${l} to ${w}! ${p} is desperate for revenge today!`,
    (p: string, o: string, _w: number, l: number) => `${o} has had ${p}'s number with ${l} wins! Can ${p} flip the script?`,
    (p: string, o: string) => `${o} dominates the rivalry! But ${p} has that look in their eye — revenge is sweet!`,
    (p: string, o: string) => `${p} trails in the head-to-head! But upsets happen! This could be the day against ${o}!`,
    (p: string, o: string) => `${o} owns this rivalry! But ${p} is coming in with fire! Watch out!`,
  ],
  even: [
    (p: string, o: string, w: number) => `All square at ${w} wins each! ${p} and ${o} are perfectly matched!`,
    (p: string, o: string) => `Dead even! Neither ${p} nor ${o} has the edge! Who breaks the tie today?`,
    (p: string, o: string) => `The head-to-head is locked! ${p} versus ${o} — this one could go either way!`,
    (p: string, o: string) => `Equal records! ${p} and ${o} know each other too well! What a contest this will be!`,
    (p: string, o: string) => `Nothing separates them in the stats! ${p} and ${o} are evenly matched rivals!`,
  ],
};

export const PRE_MATCH_TOSS = [
  (winner: string, choice: string) => `${winner} wins the toss and has elected to ${choice} first! A crucial decision!`,
  (winner: string, choice: string) => `The coin goes up, the coin comes down — ${winner} wins! They choose to ${choice} first!`,
  (winner: string, choice: string) => `${winner} calls it right! Elects to ${choice} first — interesting strategic choice!`,
  (winner: string, choice: string) => `Toss goes to ${winner}! They'll ${choice} first! The battle plan is set!`,
  (winner: string, choice: string) => `${winner} wins the all-important toss! They want to ${choice} first! Smart thinking!`,
  (winner: string, choice: string) => `The toss falls ${winner}'s way! Choosing to ${choice} first — let's see if it pays off!`,
  (winner: string, choice: string) => `${winner} takes the toss! ${choice.charAt(0).toUpperCase() + choice.slice(1)}ting first is the call! Game on!`,
  (winner: string, choice: string) => `Good fortune at the toss for ${winner}! They'll ${choice} first! Exciting decision!`,
];

export const PRE_MATCH_GO = [
  (batter: string) => `${batter} faces the first ball! Let the battle begin! May the best player win!`,
  (batter: string) => `Here we go! ${batter} on strike! The stadium holds its breath!`,
  (batter: string) => `${batter} takes guard! The bowler steams in! GAME ON!`,
  (batter: string) => `The moment is here! ${batter} faces up! Let's play cricket!`,
  (batter: string) => `${batter} ready at the crease! The bowler marks his run-up! It's GO TIME!`,
  (batter: string) => `All eyes on ${batter}! First ball of the match! HERE WE GO!`,
  (batter: string) => `${batter} adjusts the helmet, takes stance! Play! Let's go!`,
  (batter: string) => `The first ball is about to be delivered to ${batter}! Excitement at fever pitch!`,
];

// ─── Post-match expanded commentary ─────────────────────────────

export const POST_WIN_EXPANDED = [
  (p: string, ps: number, os: number) => `What a magnificent victory by ${p}! Scoring ${ps} against ${os}! A performance that will be talked about for years!`,
  (p: string) => `${p} takes the match! The crowd is on their feet! Absolutely sensational cricket! What a player!`,
  (p: string, _ps: number, os: number) => `${p} has conquered today! The opponent managed just ${os}! Complete domination from start to finish!`,
  (p: string, ps: number) => `A superb ${ps} runs and the match belongs to ${p}! The champion celebrates in style!`,
  (p: string) => `${p} rises to the occasion! When it mattered most, they delivered! That's the mark of a true champion!`,
  (p: string, ps: number, os: number) => `${p} finishes with ${ps} against ${os}! The gap tells the story — absolute class!`,
];

export const POST_LOSS_EXPANDED = [
  (_p: string, o: string, ps: number, os: number) => `${o} wins the match with ${os} runs against ${ps}! What a performance from the opposition!`,
  (p: string) => `${p} fought hard but couldn't pull it off. Head held high, though! Every champion has bad days!`,
  (p: string, o: string) => `${o} proves too strong for ${p} today! But this isn't the end — it's fuel for the comeback!`,
  (p: string, _o: string, ps: number, os: number) => `${p} falls short with ${ps} against ${os}! Tough day but the lessons are valuable!`,
  (p: string, o: string) => `${o} celebrates while ${p} reflects. That's cricket — unpredictable and beautiful!`,
  (_p: string, o: string) => `${o} was simply too good today! Hats off to a worthy winner!`,
];

export const POST_DRAW_EXPANDED = [
  (p: string, o: string) => `It's a tie! ${p} and ${o} couldn't be separated! What an incredible drama!`,
  (_p: string, _o: string) => `Incredible! Neither side gives in! A match for the ages! Both deserve the spotlight!`,
  (p: string, o: string) => `Level pegging! ${p} and ${o} gave everything! The fans got their money's worth!`,
  (p: string, o: string) => `A draw! ${p} and ${o} fought tooth and nail! Neither could break through!`,
  (_p: string, _o: string) => `Same score! Same heart! Same determination! What a contest between two warriors!`,
  (p: string, o: string) => `Tied! ${p} and ${o} will have to settle this another day! The rivalry grows!`,
];

// ─── PvP rage-bait expanded scenarios ────────────────────────────

export const PVP_RAGE_WIN = [
  (p: string, o: string) => `${o} got absolutely cooked! 🍳 ${p} served a masterclass in demolition!`,
  (p: string, o: string) => `${p} said 'sit down' and ${o} had no choice but to comply! 💀🪑`,
  (p: string, o: string) => `${o} needs a GPS because ${p} just sent them to another dimension! 🌌`,
  (p: string, o: string) => `${p} was playing chess while ${o} was playing checkers! 🧠`,
  (p: string, o: string) => `${o} thought they could compete? That's the funniest thing all day! ${p} dominates!`,
  (p: string, o: string) => `${p} didn't just win — they made ${o} question their life choices! 😂`,
  (p: string, o: string) => `${o} should consider a different hobby. ${p} made it look TOO easy! 🎭`,
  (p: string, o: string) => `${p} collected ${o}'s soul with that performance! 👻`,
  (p: string, o: string) => `${o} was the participation trophy today. ${p} took the real one! 🏆`,
  (p: string, o: string) => `${p} absolutely VIOLATED ${o}'s cricket career! Someone call an ambulance! 🚑`,
  // Indian cricket culture
  (p: string, o: string) => `${o} just graduated from the Dinda Academy of Getting Smashed! ${p} was the professor! 🎓`,
  (p: string, o: string) => `${p} channeled prime Dhoni — cool, calm, and ${o} is absolutely destroyed! Thala for a reason! 🦁`,
  (p: string, o: string) => `${o} bowled like it was a friendly gully cricket match. ${p} treated it like an IPL final! 🏏`,
  (p: string, o: string) => `${p} hit ${o} for more sixes than Yuvraj hit Stuart Broad! That's INTENT™! 💥`,
  (p: string, o: string) => `${o} needs chai and a timeout after that beating from ${p}! ☕💀`,
  (p: string, o: string) => `${p} played like Kohli on a revenge spree — ${o} never stood a chance! 👑`,
  (p: string, o: string) => `${o} got Mankaded, Bamboozled, and Humiliated by ${p}! Triple combo! 🎪`,
  (p: string, o: string) => `${p} turned ${o} into a meme! Screenshot this scoreboard! 📱😂`,
  (p: string, o: string) => `Even the third umpire couldn't save ${o} from ${p}'s wrath! All decisions FINAL! 🔴`,
  (p: string, o: string) => `${o}'s batting average against ${p} is lower than the team bus number! 🚌`,
  // Universal savage
  (p: string, o: string) => `${p} speed-ran a victory and ${o} was just a tutorial boss! 🎮`,
  (p: string, o: string) => `${o} brought a spoon to a sword fight! ${p} is RUTHLESS! ⚔️`,
  (p: string, o: string) => `Scientists confirm: ${o}'s chance of beating ${p} is statistically zero! 📊`,
  (p: string, o: string) => `${p} won so hard the scoreboard filed a complaint! ${o} is finished! 📋`,
  (p: string, o: string) => `${o}'s gameplay was like WiFi in a tunnel — completely disconnected! ${p} feasts! 📶`,
  (p: string, o: string) => `${p} made ${o} look like an NPC in a cutscene! No control whatsoever! 🤖`,
  (p: string, o: string) => `If ${o}'s performance was a movie, critics would give it 1 star. ${p} is the blockbuster! ⭐`,
  (p: string, o: string) => `${o} rage-quit mentally 3 balls in. ${p} just kept farming! 🌾`,
  (p: string, o: string) => `${p} didn't break a sweat. ${o} broke everything else though! 💔`,
  (p: string, o: string) => `Autopsy report: ${o}'s innings — cause of death: ${p}! ☠️`,
];

export const PVP_RAGE_LOSS = [
  (p: string, o: string) => `${p} thought they had it... NOPE! ${o} says not today! 🤡`,
  (p: string, o: string) => `${o} made ${p} look like a complete rookie! Back to training! 😂`,
  (p: string, o: string) => `${p} got absolutely demolished! ${o} didn't even break a sweat! 💀`,
  (p: string, o: string) => `${p}'s confidence walked in the room and ${o} showed it the exit! 🚪`,
  (p: string, o: string) => `${o} sent ${p} packing! Maybe practice mode is more your speed? 📵`,
  (p: string, o: string) => `${p} talked the talk but ${o} walked the walk! Humiliation complete! 😤`,
  (p: string, o: string) => `${o} just added ${p} to their highlight reel of victims! 🎬`,
  (p: string, o: string) => `${p} brought a plastic bat to a steel bat fight! ${o} domination! 🔨`,
  (p: string, o: string) => `${o} treated ${p} like a training dummy! Brutal! 💥`,
  (p: string, o: string) => `${p} needs to delete the app and start fresh after what ${o} just did! 📱`,
  // Indian cricket culture
  (p: string, o: string) => `${p} got the full Dinda treatment! ${o} smashed every ball out of the park! 🎓`,
  (p: string, o: string) => `${o} played like Sachin in '03 World Cup — ${p} was just another bowler! 🏆`,
  (p: string, o: string) => `${p} got treated like a net bowler at an IPL practice session by ${o}! 🏏`,
  (p: string, o: string) => `${o} said 'aaj karke aaya' and absolutely bodied ${p}! Hindi commentary mode! 🎤`,
  (p: string, o: string) => `${p} got reverse-swept, paddle-scooped, and embarrassed by ${o}! Gully cricket special! 😵`,
  (p: string, o: string) => `${o} played like Bumrah, batted like ABD. ${p} was just... there! 🌟`,
  (p: string, o: string) => `${p}'s bowling was so bad, ${o}'s grandma could've scored more! Nani would be proud! 👵`,
  (p: string, o: string) => `${o} made ${p} look like they've never held a bat! Time for some nets! 🥅`,
  // Universal savage
  (p: string, o: string) => `${p} was basically a spectator in their own match! ${o} ran the show! 🎪`,
  (p: string, o: string) => `If losing was an art form, ${p} just painted the Mona Lisa! ${o} is the museum! 🖼️`,
  (p: string, o: string) => `${p}'s game plan was to lose speedily, apparently! ${o} helped! 💨`,
  (p: string, o: string) => `${o} won and ${p} learned a valuable lesson: they're not that guy! 🙅`,
  (p: string, o: string) => `${p} typed 'gg' but meant 'gg my dignity'! ${o} took everything! 💀`,
  (p: string, o: string) => `Scoreboard says ${o} wins. Reality says ${p} never had a chance! 📊`,
  (p: string, o: string) => `${p} was loading... buffering... and ${o} already won! 🔄`,
  (p: string, o: string) => `${o} made it look like ${p}'s controller was unplugged! Total domination! 🎮`,
  (p: string, o: string) => `${p} needs a support group after that performance! ${o} is the villain origin story! 😈`,
  (p: string, o: string) => `Even autocorrect couldn't fix ${p}'s gameplay! ${o} is unstoppable! 📝`,
  (p: string, o: string) => `${p} folded faster than a lawn chair! ${o} didn't even try! 🪑`,
  (p: string, o: string) => `${o} won so convincingly, even ${p}'s fans switched sides! 🏳️`,
];

export const PVP_RAGE_DRAW = [
  (p: string, o: string) => `Neither ${p} nor ${o} could finish the job! Both equally mid! 😐`,
  (_p: string, _o: string) => `A draw? In THIS economy? Play again cowards! ⚔️`,
  (p: string, o: string) => `${p} and ${o} are like two people fighting over the last samosa — neither wins! 🥟`,
  (p: string, o: string) => `Both ${p} and ${o} thought they were better... plot twist: neither is! 📺`,
  (p: string, o: string) => `${p} and ${o} are perfectly matched — perfectly mediocre! 😂`,
  (_p: string, _o: string) => `A tie? Both of you should be embarrassed! Neither could close it out! 😭`,
  (p: string, o: string) => `${p} and ${o} played the most indecisive match of all time! DRAW! 🤦`,
  (_p: string, _o: string) => `The only thing worse than losing is not even being able to win or lose! DRAW! 😑`,
  // Indian cricket culture
  (p: string, o: string) => `${p} and ${o} played like India vs South Africa in every ICC event — HEARTBREAK for both! 💔`,
  (_p: string, _o: string) => `This match had more drama than an IPL auction but less result! Tied! 📺`,
  (p: string, o: string) => `${p} and ${o} both channeled Rahul Dravid — patient, disciplined, and absolutely TIED! 🧱`,
  (_p: string, _o: string) => `Bhai, Super Over karo! This tie is unacceptable in gully cricket! 🏏`,
  (p: string, o: string) => `Both ${p} and ${o} had the intent™ but zero execution! Classic tied match! 😤`,
  (p: string, o: string) => `${p} and ${o} are like two auto-rickshaws racing — lots of noise, same destination: DRAW! 🛺`,
  (p: string, o: string) => `DRS can't review this draw! Both ${p} and ${o} are equally guilty! 📺🔴`,
  // Universal savage
  (_p: string, _o: string) => `Imagine trying THIS hard and still ending up equal! Peak mediocrity! 🏔️`,
  (p: string, o: string) => `${p} and ${o} are the living proof that effort doesn't always equal results! 📉`,
  (p: string, o: string) => `Both ${p} and ${o} speedran a tie! Any% draw completion! 🎮`,
  (_p: string, _o: string) => `The scoreboard had one job — pick a winner. It failed too! 📊`,
  (p: string, o: string) => `${p} and ${o} both deserve participation trophies for this tie! 🥉🥉`,
  (_p: string, _o: string) => `This draw was so boring, the WiFi thought about disconnecting! 📶`,
  (p: string, o: string) => `${p} and ${o} tied? The algorithm is having a meltdown trying to rank this! 🤖`,
  (_p: string, _o: string) => `A tie! Both players' highlight reels will be suspiciously empty! 🎬`,
  (p: string, o: string) => `${p} and ${o} fought to a draw — proof that mediocrity loves company! 🤝`,
];

export const PVP_CLOSING = [
  "GGs only... or is it? 😈 REMATCH?",
  "Think you can handle a rematch? Prove it! 💪",
  "Best of three? Best of five? Let's settle this! 🔥",
  "That was just the warm-up. Real game next? 😏",
  "REMATCH button is right there... if you're brave enough! 👀",
  "One more? Or are you scared? 😤 Hit REMATCH!",
  "The rivalry continues! Settle the score — play again! ⚔️",
  "You really gonna leave it like that? REMATCH NOW! 🔄",
  "Neither of you can walk away from this. Play again! 🏏",
  "The crowd demands a rematch! Don't disappoint them! 🏟️",
  "Unfinished business! That rematch button is calling your name! 📞",
  "Your pride is on the line. One more game? 👑",
  "Walk away now and this score defines you FOREVER! 😱 Rematch?",
  "Bhai ek aur? Last wala pakka last! (Spoiler: it's never the last) 😂",
  "The cricket gods demand more entertainment! REMATCH! ⚡",
];

// ─── Stats analysis commentary ──────────────────────────────────

export const STATS_SIXES = [
  (p: string, n: number) => `${p} smashed ${n} massive sixes! 💥 The ball went into orbit ${n} times!`,
  (p: string, n: number) => `${n} sixes from ${p}! The crowd caught souvenirs tonight!`,
  (p: string, n: number) => `Power hitting on display! ${p} launched ${n} maximums!`,
  (p: string, n: number) => `${p} cleared the boundary ${n} times! Phenomenal six-hitting!`,
];

export const STATS_FOURS = [
  (p: string, n: number) => `${n} boundaries found the fence! ${p} was timing it beautifully!`,
  (p: string, n: number) => `${p} hit ${n} fours! The boundary rope had no rest tonight!`,
  (p: string, n: number) => `${n} cracking fours from ${p}! Gap-finding at its finest!`,
  (p: string, n: number) => `${p} raced to ${n} boundaries! The fielders were mere spectators!`,
];

export const STATS_SR = [
  (p: string, sr: number, balls: number) => `Strike rate of ${sr} off ${balls} balls! ${p} was in commanding form!`,
  (p: string, sr: number, balls: number) => `${p} faced ${balls} balls at a strike rate of ${sr}! Impressive composure!`,
  (_p: string, sr: number) => `A strike rate of ${sr}! That's aggressive cricket at its finest!`,
  (p: string, sr: number) => `${p} scored at ${sr} per 100 balls! The scoreboard was always ticking!`,
];

export const STATS_BDRY_PCT = [
  (p: string, pct: number) => `Over ${pct} percent of runs came from boundaries! ${p} was in destructive mode! 🔥`,
  (_p: string, pct: number) => `${pct} percent boundary rate! That's pure aggression!`,
  (p: string, pct: number) => `${p} scored ${pct}% of runs in boundaries! The bowlers had nowhere to hide!`,
];

export const STATS_BIGGEST = [
  "The biggest shot of the innings — a towering SIX! ☄️ The ball needed a passport!",
  "A monstrous SIX was the biggest shot! The crowd is still looking for the ball! ☄️",
  "SIX! The biggest shot of the match! It went out of the stadium! ☄️",
];

function pick(arr: string[]): string {
  return arr[Math.floor(Math.random() * arr.length)];
}

export function getCommentary({ game, result }: CommentaryContext): string {
  if (game.phase === "finished") {
    if (game.result === "win") return pick(WIN_COMMENTS);
    if (game.result === "loss") return pick(LOSS_COMMENTS);
    return pick(DRAW_COMMENTS);
  }

  if (result.runs === "OUT") {
    return game.isBatting ? pick(OUT_BATTING) : pick(OUT_BOWLING);
  }

  const runs = typeof result.runs === "number" ? result.runs : 0;
  const runsKey = String(Math.abs(runs));

  if (game.isBatting) {
    const base = pick(BATTING_RUNS[runsKey] || BATTING_RUNS["0"]);
    if (game.target && game.userScore < game.target) {
      const need = game.target - game.userScore;
      if (need <= 10) return `${base} Need ${need} more to win!`;
      if (Math.random() > 0.6) return `${base} ${pick(CHASE_COMMENTS)}`;
    }
    if (game.userScore > 0 && game.userScore % 50 === 0) {
      return `${base} FIFTY UP! 🎉 ${game.userScore} runs!`;
    }
    return base;
  } else {
    const base = pick(BOWLING_RUNS[runsKey] || BOWLING_RUNS["0"]);
    if (game.target && game.aiScore < game.target) {
      const need = game.target - game.aiScore;
      if (need <= 5) return `${base} AI needs just ${need} more!`;
    }
    return base;
  }
}

export function getInningsChangeCommentary(game: GameState): string {
  if (game.currentInnings === 2 && game.target) {
    if (game.isBatting) {
      return `🏏 Second innings! Chase ${game.target} to win!`;
    } else {
      return `🎯 Your turn to bowl! Defend ${game.target} runs!`;
    }
  }
  return game.isBatting ? "🏏 You're batting! Score big!" : "🎯 You're bowling! Get 'em out!";
}
